"""Utility functions to read and write .bxsf files.

BXSF format specification: http://www.xcrysden.org/doc/XSF.html#__toc__14

Grid convention (from Wannier90 / XCrysDen spec):
  - Dimensions are written as NX NY NZ
  - Eigenvalue data is stored in C order: NX slowest, NZ fastest
  - Spanning vectors are written as rows: one vector per line (x y z)
  - Internally, span_vectors is stored column-major: span_vectors[:, i] = i-th vector
"""

import numpy as np


def read_bxsf(filename):
    """Read a .bxsf file.

    Returns
    -------
    fermi_energy : float
        Fermi energy in eV.
    origin : ndarray, shape (3,)
        Origin of the grid in Å⁻¹.
    span_vectors : ndarray, shape (3, 3)
        Spanning vectors in Å⁻¹, stored column-major: span_vectors[:, i] is
        the i-th spanning vector.
    X : ndarray, shape (nx,)
        Fractional coordinates along the first spanning vector.
    Y : ndarray, shape (ny,)
        Fractional coordinates along the second spanning vector.
    Z : ndarray, shape (nz,)
        Fractional coordinates along the third spanning vector.
    E : ndarray, shape (n_bands, nx, ny, nz)
        Eigenvalues at each grid point.
    """
    with open(filename, encoding="utf-8") as io:
        fermi_energy = None
        origin = None
        span_vectors = None
        X = Y = Z = None
        E = None

        while True:
            line = io.readline()
            if not line:
                break
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            if "BEGIN_INFO" in line:
                while True:
                    line = io.readline().strip()
                    if line and not line.startswith("#"):
                        break
                assert line.startswith("Fermi Energy:")
                fermi_energy = float(line.split(":")[1].strip())
                line = io.readline().strip()
                assert line == "END_INFO"

            elif "BEGIN_BLOCK_BANDGRID_3D" in line:
                _ = io.readline().strip()  # comment line
                line = io.readline().strip()
                assert line.startswith("BEGIN_BANDGRID_3D")

                n_bands = int(io.readline().strip())
                n_x, n_y, n_z = map(int, io.readline().strip().split())
                origin = np.array(list(map(float, io.readline().strip().split())))

                span_vectors = np.zeros((3, 3))
                for i in range(3):
                    line = io.readline().strip()
                    span_vectors[:, i] = np.array(list(map(float, line.split())))

                E = np.zeros((n_bands, n_x, n_y, n_z))

                for ib in range(n_bands):
                    line = io.readline().strip()
                    assert line == f"BAND: {ib + 1}"
                    idx = 0
                    Eib = []
                    while idx < n_x * n_y * n_z:
                        line = io.readline().strip().split()
                        ncol = len(line)
                        Eib += list(map(float, line))
                        idx += ncol
                    assert idx == n_x * n_y * n_z
                    # NZ is fastest-varying (C order), matching the XCrysDen/Wannier90 convention
                    E[ib] = np.reshape(Eib, (n_x, n_y, n_z))

                assert "END_BANDGRID_3D" in io.readline().strip()
                assert io.readline().strip() == "END_BLOCK_BANDGRID_3D"

        if E is not None:
            _, n_x, n_y, n_z = E.shape
            X = np.linspace(0, 1, n_x)
            Y = np.linspace(0, 1, n_y)
            Z = np.linspace(0, 1, n_z)

        return fermi_energy, origin, span_vectors, X, Y, Z, E


def write_bxsf(filename: str, fermi_energy: float, origin, span_vectors, E):
    """Write a .bxsf file.

    Parameters
    ----------
    filename : str
        Path of the file to write.
    fermi_energy : float
        Fermi energy in eV.
    origin : array-like, shape (3,)
        Origin of the grid in Å⁻¹.
    span_vectors : ndarray, shape (3, 3)
        Spanning vectors in Å⁻¹, stored column-major: span_vectors[:, i] is
        the i-th spanning vector.
    E : ndarray, shape (n_bands, nx, ny, nz)
        Eigenvalues at each grid point.
    """
    if len(origin) != 3:
        raise ValueError("origin must be a 3-element vector")
    if np.asarray(span_vectors).shape != (3, 3):
        raise ValueError("span_vectors must be a 3x3 matrix")

    with open(filename, "w", encoding="utf-8") as io:
        io.write("BEGIN_INFO\n")
        io.write("  # Generated by fermisurface-utils bxsf writer\n")
        io.write(f"  Fermi Energy: {fermi_energy:21.16f}\n")
        io.write("END_INFO\n\n")

        io.write("BEGIN_BLOCK_BANDGRID_3D\n")
        io.write("fermisurface_utils\n")
        io.write("BEGIN_BANDGRID_3D_fermi\n")

        n_bands, n_x, n_y, n_z = E.shape
        io.write(f"{n_bands}\n")
        io.write(f"{n_x} {n_y} {n_z}\n")
        io.write(f"{origin[0]:12.7f} {origin[1]:12.7f} {origin[2]:12.7f}\n")
        for i in range(3):
            io.write(
                f"{span_vectors[0, i]:12.7f} {span_vectors[1, i]:12.7f} {span_vectors[2, i]:12.7f}\n"
            )

        for ib in range(n_bands):
            io.write(f"BAND: {ib + 1}\n")
            ncol = 0
            for i in range(n_x):
                for j in range(n_y):
                    for k in range(n_z):
                        io.write(f" {E[ib, i, j, k]:16.8e}")
                        ncol += 1
                        if ncol == 6:
                            io.write("\n")
                            ncol = 0
            if ncol != 0:
                io.write("\n")

        io.write("END_BANDGRID_3D\n")
        io.write("END_BLOCK_BANDGRID_3D\n")
